# Metadata
solution:
  name: "Object Detection Solution"
  description: "A solution for object detection tasks."
  # docker_image: "supervisely/base-py-sdk:6.73.398"
  # instance_version: "6.13.8"
  # version: "1.0.0"

# Graph settings
settings:
  environment:
    variables:
      PROJECT_ID: "{{ $PROJECT_ID | default('null') }}"
  graph:
    height: "1800px"
    width: "100%"
    grid: true
  positions: &positions
    auto_import: &auto_import_position { x: 770, y: 30 }
    cloud_import: &cloud_import_position { x: 430, y: 30 }
    input_project: &input_project_position { x: 620, y: 150 }
    open_ai_clip: &open_ai_clip_position { x: 150, y: 270 }
    ai_index: &ai_index_position { x: 380, y: 270 }
    smart_sampling: &smart_sampling_position { x: 612, y: 340 }
    labeling_project: &labeling_project_position { x: 620, y: 470 }
    labeling_queue: &labeling_queue_position { x: 612, y: 660 }
    labeling_queue_performance:
      &labeling_queue_performance_position { x: 950, y: 660 }
    train_val_split: &train_val_split_position { x: 612, y: 950 }
    move_labeled_data: &move_labeled_data_position { x: 612, y: 1040 }
    training_project: &training_project_position { x: 600, y: 1140 }
    training_project_stats: &training_project_stats_position { x: 950, y: 1140 }
    data_versioning: &data_versioning_position { x: 612, y: 1300 }
    pretrained_models: &pretrained_models_position { x: 612, y: 1390 }
    training_experiment: &training_experiment_position { x: 735, y: 1450 }
    training_artifacts: &training_artifacts_position { x: 735, y: 1520 }
    training_evaluation: &training_evaluation_position { x: 735, y: 1590 }
    all_experiments: &all_experiments_position { x: 1150, y: 1390 }
    re_evaluate: &re_evaluate_position { x: 1300, y: 1450 }
    evaluation_report: &re_evaluation_report_position { x: 1460, y: 1520 }
    compare_models: &compare_models_position { x: 1334, y: 1640 }
    comparison_report: &comparison_report_position { x: 1460, y: 1700 }
    email_notification: &email_notification_position { x: 1460, y: 1760 }
    deploy_pretrained_model:
      &deploy_pretrained_model_position { x: 1220, y: 340 }
    deploy_custom_model: &deploy_custom_model_position { x: 1220, y: 522 }
    # deploy
    pre_labeling: &pre_labeling_position { x: 850, y: 425 }
  defaults: &defaults
    width: 250
    connection_settings: &defaults_connection_settings
      type: "smoothstep"

# All nodes in the graph
nodes:
  # - id: "state_initialization"
    # placeholder for future state initialization node

  - id: &auto_import_id "auto_import" # unique ID for the node
    name: &auto_import_name "Manual D&D Import"
    description: &auto_import_description "Each import creates a dataset folder in the Input Project, centralising all incoming data and easily managing it over time. Automatically detects 10+ annotation formats."
    type: "supervisely.solution.AutoImportNode" # type of the node to import
    parameters:
      title: *auto_import_name
      description: *auto_import_description
      project_id: "{{ $PROJECT_ID | default('null') }}"
      # tooltip_position: "right"
      <<: *auto_import_position # x, y
      icon: "mdi mdi-arrow-down-bold-circle"
      icon_color: "#1976D2"
      icon_bg_color: "#E3F2FD"

  - id: &cloud_import_id "cloud_import" # unique ID for the node
    type: "supervisely.solution.CloudImportNode" # type of the node to import
    parameters:
      project_id: "{{ $PROJECT_ID | default('null') }}"
      <<: *cloud_import_position # x, y

  - id: &input_project_id "input_project"
    type: "supervisely.solution.InputProjectNode"
    parameters:
      project_id: "{{ $PROJECT_ID | default('null') }}"
      <<: *input_project_position # x, y

  # - id: &open_ai_clip_id "open_ai_clip"
  #   type: "supervisely.solution.OpenAIClipServiceNode"
  #   parameters:
  #     <<: *open_ai_clip_position # x, y

  # - id: &ai_index_id "ai_index"
  #   type: "supervisely.solution.AiIndexNode"
  #   parameters:
  #     <<: *ai_index_position # x, y
  #     project_id: "{{ $PROJECT_ID | default('null') }}"

  - id: &smart_sampling_id "smart_sampling"
    type: "supervisely.solution.SmartSamplingNode"
    parameters:
      project_id: "{{ $PROJECT_ID | default('null') }}"
      dst_project: "{{ $LABELING_PROJECT_ID | default('null') }}"
      <<: *smart_sampling_position # x, y

  - id: &labeling_project_id "labeling_project"
    type: "supervisely.solution.LabelingProjectNode"
    parameters:
      project_id: "{{ $LABELING_PROJECT_ID | default('null') }}"
      <<: *labeling_project_position

  - id: &labeling_queue_id "labeling_queue"
    type: "supervisely.solution.LabelingQueueNode"
    parameters:
      <<: *labeling_queue_position
      queue_id: "{{ $LABELING_QUEUE_ID | default('null') }}"
      collection_id: "{{ $LABELING_COLLECTION_ID | default('null') }}"

  - id: &labeling_queue_performance_id "labeling_queue_performance"
    type: "supervisely.solution.LabelingQueuePerformanceNode"
    parameters:
      <<: *labeling_queue_performance_position
      queue_id: "{{ $LABELING_QUEUE_ID | default('null') }}"

  - id: &train_val_split_id "train_val_split"
    type: "supervisely.solution.TrainValSplitNode"
    parameters:
      dst_project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      <<: *train_val_split_position

  - id: &move_labeled_data_id "move_labeled_data"
    type: "supervisely.solution.MoveLabeledNode"
    parameters:
      src_project_id: "{{ $LABELING_PROJECT_ID | default('null') }}"
      dst_project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      <<: *move_labeled_data_position

  - id: &training_project_id "training_project"
    type: "supervisely.solution.TrainingProjectNode"
    parameters:
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      <<: *training_project_position

  - id: &training_project_stats_id "training_project_stats"
    type: "supervisely.solution.QAStatsNode"
    parameters:
      <<: *training_project_stats_position
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      link: "/projects/{{ $TRAINING_PROJECT_ID | default('null') }}/stats/datasets"

  - id: &data_versioning_id "data_versioning"
    type: "supervisely.solution.DataVersioningNode"
    parameters:
      <<: *data_versioning_position
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      link: "/projects/{{ $TRAINING_PROJECT_ID | default('null') }}/versions"

  - id: &pretrained_models_id "pretrained_models"
    type: "supervisely.solution.BaseTrainNode"
    parameters:
      <<: *pretrained_models_position
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"

  - id: &training_experiment_id "training_experiment"
    type: "supervisely.solution.TrainingExperimentNode"
    parameters:
      <<: *training_experiment_position

  - id: &training_artifacts_id "training_artifacts"
    type: "supervisely.solution.TrainingArtifactsNode"
    parameters:
      <<: *training_artifacts_position

  - id: &training_evaluation_id "training_evaluation"
    type: "supervisely.solution.TrainingEvaluationReportNode"
    parameters:
      <<: *training_evaluation_position

  - id: &all_experiments "all_experiments"
    type: "supervisely.solution.AllExperimentsNode"
    parameters:
      <<: *all_experiments_position

  - id: &re_evaluate "re_evaluate"
    type: "supervisely.solution.EvaluationNode"
    parameters:
      <<: *re_evaluate_position
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"

  - id: &re_evaluation_report "re_evaluation_report"
    type: "supervisely.solution.EvaluationReportNode"
    parameters:
      description: "View the evaluation report of the model."
      <<: *re_evaluation_report_position

  - id: &compare_models "compare_models"
    type: "supervisely.solution.CompareModelsNode"
    parameters:
      project_id: "{{ $TRAINING_PROJECT_ID | default('null') }}"
      <<: *compare_models_position

  - id: &comparison_report "comparison_report"
    type: "supervisely.solution.EvaluationReportNode"
    parameters:
      description: "View the comparison report of the models."
      <<: *comparison_report_position

  - id: &email_notification "email_notification"
    type: "supervisely.solution.EmailNotificationNode"
    parameters:
      <<: *email_notification_position

  - id: &deploy_pretrained_model_id "deploy_pretrained_model"
    type: "supervisely.solution.DeployPretrainedModelNode"
    parameters:
      <<: *deploy_pretrained_model_position

  - id: &deploy_custom_model_id "deploy_custom_model"
    type: "supervisely.solution.DeployCustomModelNode"
    parameters:
      <<: *deploy_custom_model_position

  - id: &pre_labeling_id "pre_labeling"
    type: "supervisely.solution.PreLabelingNode"
    parameters:
      <<: *pre_labeling_position # x, y

connections:
  - id: "edge-auto_import-to-input_project"
    source: *auto_import_id
    target: *input_project_id
    <<: *defaults_connection_settings

  - id: "edge-cloud_import-to-input_project"
    source: *cloud_import_id
    target: *input_project_id
    <<: *defaults_connection_settings

  # - id: "edge-input_project-to-ai_index"
  #   source: *input_project_id
  #   target: *ai_index_id
  #   <<: *defaults_connection_settings
  #   style:
  #     strokeDasharray: "8,8"

  # - id: "edge-open_ai_clip-to-ai_index"
  #   source: *open_ai_clip_id
  #   target: *ai_index_id
  #   <<: *defaults_connection_settings
  #   style:
  #     # stroke: "#B1B1B6"
  #     # strokeWidth: 1
  #     strokeDasharray: "8,8"

  # - id: "edge-ai_index-to-smart_sampling"
  #   source: *ai_index_id
  #   target: *smart_sampling_id
  #   <<: *defaults_connection_settings
  #   style:
  #     strokeDasharray: "8,8"

  - id: "edge-input_project-to-smart_sampling"
    source: *input_project_id
    target: *smart_sampling_id
    <<: *defaults_connection_settings

  - id: "edge-smart_sampling-to-labeling_project"
    source: *smart_sampling_id
    target: *labeling_project_id
    <<: *defaults_connection_settings

  - id: "edge-labeling_project-to-labeling_queue"
    source: *labeling_project_id
    target: *labeling_queue_id
    <<: *defaults_connection_settings

  - id: "edge-labeling_queue-to-labeling_queue_performance"
    source: *labeling_queue_id
    target: *labeling_queue_performance_id
    <<: *defaults_connection_settings
    style:
      strokeDasharray: "8,8"

  - id: "edge-labeling_queue-to-train_val_split"
    source: *labeling_queue_id
    target: *train_val_split_id
    <<: *defaults_connection_settings

  - id: "edge-train_val_split-to-move_labeled_data"
    source: *train_val_split_id
    target: *move_labeled_data_id
    <<: *defaults_connection_settings

  - id: "edge-move_labeled_data-to-training_project"
    source: *move_labeled_data_id
    target: *training_project_id
    <<: *defaults_connection_settings

  - id: "edge-training_project-to-training_project_stats"
    source: *training_project_id
    target: *training_project_stats_id
    <<: *defaults_connection_settings
    style:
      strokeDasharray: "8,8"

  - id: "edge-training_project-to-data_versioning"
    source: *training_project_id
    target: *data_versioning_id
    <<: *defaults_connection_settings

  - id: "edge-data_versioning-to-pretrained_models"
    source: *data_versioning_id
    target: *pretrained_models_id
    <<: *defaults_connection_settings

  - id: "edge-pretrained_models-to-training_experiment"
    source: *pretrained_models_id
    target: *training_experiment_id
    <<: *defaults_connection_settings

  - id: "edge-pretrained_models-to-training_artifacts"
    source: *pretrained_models_id
    target: *training_artifacts_id
    <<: *defaults_connection_settings

  - id: "edge-pretrained_models-to-training_evaluation"
    source: *pretrained_models_id
    target: *training_evaluation_id
    <<: *defaults_connection_settings

  - id: "edge-pretrained_models-to-all_experiments"
    source: *pretrained_models_id
    target: *all_experiments
    <<: *defaults_connection_settings

  - id: "edge-pretrained_models-to-compare_models"
    source: *pretrained_models_id
    target: *compare_models
    <<: *defaults_connection_settings

  - id: "edge-all_experiments-to-re_evaluate"
    source: *all_experiments
    target: *re_evaluate
    <<: *defaults_connection_settings

  - id: "edge-re_evaluate-to-re_evaluation_report"
    source: *re_evaluate
    target: *re_evaluation_report
    <<: *defaults_connection_settings

  - id: "edge-re_evaluate-to-compare_models"
    source: *re_evaluate
    target: *compare_models
    <<: *defaults_connection_settings

  - id: "edge-compare_models-to-comparison_report"
    source: *compare_models
    target: *comparison_report
    <<: *defaults_connection_settings

  - id: "edge-compare_models-to-email_notification"
    source: *compare_models
    target: *email_notification
    <<: *defaults_connection_settings

  - id: "edge-deploy_pretrained_model-to-pre_labeling"
    source: *deploy_pretrained_model_id
    target: *pre_labeling_id
    <<: *defaults_connection_settings

  - id: "edge-smart_sampling-to-pre_labeling"
    source: *smart_sampling_id
    target: *pre_labeling_id
    <<: *defaults_connection_settings

  - id: "edge-pre_labeling-to-labeling_project"
    source: *pre_labeling_id
    target: *labeling_project_id
    <<: *defaults_connection_settings

  - id: "edge-compare_models-to-deploy_custom_model"
    source: *compare_models
    target: *deploy_custom_model_id
    <<: *defaults_connection_settings

  - id: "edge-deploy_custom_model-to-pre_labeling"
    source: *deploy_custom_model_id
    target: *pre_labeling_id
    <<: *defaults_connection_settings
